### ISSUE TITLE
skt: unsupported event packet: then panic

### ISSUE THREAD

**Issue by leahneukirchen** [go-ble/ble#75]
After some time (days) of running `ble.Scan`, it crashes:

```
2020/09/20 03:35:07 skt: unsupported event packet: 18 A4 C1 38 A2 6F 07 00 B0 40
 56 0B 9E 29 C1 3E 1B 02 01 00 00 FD 20 E2 CD 69 C8 0F 02 01 1A 0B FF 4C 00 09 06 03 24 C0 A8 00 05 B1 3E 0C 02 01 04 00 FD 20 E2 CD 69 C8 00 B0 3E 1B 02 01 00 00 FD 20 E2 CD 69 C8 0F 02 01 1A 0B FF 4C 00 09 06 03 24 C0 A8 00 05 B2 3E 1D 02 01 00 00 07 6F A2 38 C1 A4 11 10 16 1A 18 A4 C1 38 A2 6F 07 00 B0 40 56 0B 9E 29 C0 3E 18 02 01 04 00 07 6F A2 38 C1 A4 0C 0B 09 41 54 43 5F 41 32 36 46 30 37 C0 3E 1D 02 01 00 00 63 3D F1 38 C1 A4 11 10 16 1A 18 A4 C1 38 F1 3D
2020/09/20 03:35:07 skt: unsupported event packet: 63 00
2020/09/20 03:35:08 skt: unsupported event packet: 09 06 03 24 C0 A8 00 05
2020/09/20 03:35:09 skt: unsupported event packet: B2 3E 0C 02 01 04 00 FD 20 E2 CD 69 C8 00 B1 3E 1B 02 01 00 00 FD 20 E2 CD 69 C8 0F 02 01 1A 0B FF 4C 00 09 06 03 24 C0 A8 00 05 B2 3E 1D 02 01 00 00 63 3D F1 38 C1 A4 11 10 16 1A 18 A4 C1 38
2020/09/20 03:35:10 skt: unsupported event packet: F1 3D 63 00 FF 36 61 0C 06 90 C7 3E 18 02 01 04 00 63 3D F1 38 C1 A4 0C 0B 09 41 54 43 5F 46 31 33 44 36 33 C7 3E 1B 02 01 00 00 FD 20 E2 CD 69 C8 0F 02 01 1A 0B FF 4C 00 09 06 03 24 C0 A8
2020/09/20 03:35:10 skt: unsupported event packet: 00 05 B0 3E 1D 02 01
2020/09/20 03:35:10 skt: unsupported event packet: 00 00
2020/09/20 03:35:11 skt: unsupported event packet: 07 6F A2 38 C1 A4 11 10 16 1A 18 A4 C1 38 A2 6F 07 00 B0 40 56 0B 9E 29 BE 3E 1D 02 01 00 00 63 3D F1 38 C1 A4 11 10 16 1A 18 A4 C1 38 F1 3D 63 00 FF 36 61 0C 06 90 D5 3E 1B 02 01 00 00 FD 20 E2 CD 69 C8 0F 02 01 1A 0B FF 4C 00 09 06 03 24 C0 A8 00 05 B0 3E 1B 02 01 00 00 FD 20 E2 CD 69 C8 0F 02 01 1A 0B FF 4C 00 09 06 03 24 C0 A8 00 05
2020/09/20 03:35:14 skt: unsupported event packet: B0 3E 1A 02 01 00 01 8F 54 EB 8B 62 4E 0E 02 01 06 0A FF 4C 00 10 05 01 18 11 58 45 B0 3E 1B 02 01 00 00 FD 20 E2 CD 69 C8 0F 02 01 1A 0B FF 4C 00 09 06 03 24 C0 A8 00 05 B1 3E 1D 02 01 00 00
...
...
panic: runtime error: index out of range [1] with length 0

goroutine 19 [running]:
encoding/binary.littleEndian.Uint16(...)
        /usr/lib/go/src/encoding/binary/binary.go:53
github.com/go-ble/ble/linux/hci/evt.CommandStatus.CommandOpcode(...)
        /home/leah/.go/pkg/mod/github.com/go-ble/ble@v0.0.0-20200407180624-067514cd6e24/linux/hci/evt/evt_gen.go:62
github.com/go-ble/ble/linux/hci.(*HCI).handleCommandStatus(0xc00007fd40, 0xc000025a9b, 0x2, 0x2, 0xc000082300, 0xc00004de58)
        /home/leah/.go/pkg/mod/github.com/go-ble/ble@v0.0.0-20200407180624-067514cd6e24/linux/hci/hci.go:465 +0x26f
github.com/go-ble/ble/linux/hci.(*HCI).handleEvt(0xc00007fd40, 0xc000025a99, 0x4, 0x4, 0x44ea16, 0xc000025a98)
        /home/leah/.go/pkg/mod/github.com/go-ble/ble@v0.0.0-20200407180624-067514cd6e24/linux/hci/hci.go:371 +0x25a
github.com/go-ble/ble/linux/hci.(*HCI).handlePkt(0xc00007fd40, 0xc000025a98, 0x5, 0x5, 0xc000025a98, 0x0)
        /home/leah/.go/pkg/mod/github.com/go-ble/ble@v0.0.0-20200407180624-067514cd6e24/linux/hci/hci.go:343 +0x2b9
github.com/go-ble/ble/linux/hci.(*HCI).sktLoop(0xc00007fd40)
        /home/leah/.go/pkg/mod/github.com/go-ble/ble@v0.0.0-20200407180624-067514cd6e24/linux/hci/hci.go:311 +0x150
created by github.com/go-ble/ble/linux/hci.(*HCI).Init
        /home/leah/.go/pkg/mod/github.com/go-ble/ble@v0.0.0-20200407180624-067514cd6e24/linux/hci/hci.go:153 +0x54a
```

**Comment by estutzenberger** [comment]
Is this still relevant?

**Comment by leahneukirchen** [comment]
I think so, it last crashed 5 days ago (but on the same Git revision as in the report).

**Comment by leahneukirchen** [comment]
I'll update to HEAD and log the panics.

**Comment by estutzenberger** [comment]
We have a fork which has some better handling around advertisement handling which you might consider trying as well. It can be found here: https://github.com/rigado/ble
